### ISSUE TITLE
Did you have any success with browserify ?

### ISSUE THREAD

**Issue by chevdor** [SamDecrock/node-http-ntlm#24]
Hello Sam,

Is this module browserify-able? Was it ever tried?

I am trying that at the moment and I am getting an error from request.js:117
```OPTIONS http://myserver:81/someEndpoint``` 
My tests are fine with running in node.

**Comment by chevdor** [comment]
The problem seems to come from httpreq.
```
// check for redirects
if(res.headers.location && o.allowRedirects){
    if(o.redirectCount < o.maxRedirects){
```
due to the fact that ```res.headers``` is undefined.

**Comment by SamDecrock** [comment]
I don't think that's possible as I would need to rewrite the HTTP requests to use Ajax instead of Node.js' HTTP requests.

I don't see why you would want to use ntlm from Javascript as it is built in to all popular browsers?

**Comment by chevdor** [comment]
Hi Sam,

First of all, thanks for your answer. I did not get it to work so far.

My goal is the following:
 - make a npm package that both work as node package as well as JS lib for
the browser
 - connect to a REST API that requires ntlm

Can you expand on what you said "I don't see why you would want to use ntlm
from Javascript as it is built in to all popular browsers?" as I may simply
go the wrong way and if another option works, I would be glad to go for it.

**Comment by SamDecrock** [comment]
Well, if you go to an url that requires an NTLM authentication, your browser will automatically popup a login window where you can enter your credentials. From that point on, your browser will send headers back and forth containing that NTLM authentication allowing you access to the server's pages/content. 

Will this interface you're building be running on the same domain as the NTLM REST api's? If so, then it would be easier to send the user to a regular, NTML protected page, let them login and continue to an interface making REST calls. The browser will manage the NTLM headers until the end of the browser session.

If your interface is NOT running on the same domain as the NTLM REST api's, then you will have to configure that server's headers so that it will send a "Access-Control-Allow-Origin" header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) allowing you to access it's REST interface from another domain.

**Comment by chevdor** [comment]
Hi Sam,

Thanks for your explanations. You are right! 
I was somehow expecting httpnlm to fall back on ajax calls but I guess I can also handle that in my module.

Indeed, I need to send the proper CORS headers as I am not in the same domain but I did already validate that part.

So I close this issue as it is out of the scope of your module and I thank you for your time and explanations.
